# Generated by Django 3.2.5 on 2021-08-02 11:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('user', 'post')},
        ),
    ]
