# Generated by Django 3.2.5 on 2021-11-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_emailnotificationsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='institute',
        ),
    ]
